# Generated by Django 2.2.7 on 2022-08-16 08:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20220816_1640'),
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='articlecategory',
            table='category',
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('authorName', models.CharField(max_length=20, null=True)),
                ('authorImg', models.ImageField(blank=True, null=True, upload_to='')),
                ('articleId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('imgPath', models.ImageField(blank=True, upload_to='article/%Y%m%d')),
                ('cate', models.CharField(blank=True, max_length=100)),
                ('abstract', models.TextField()),
                ('content', mdeditor.fields.MDTextField()),
                ('view', models.PositiveIntegerField()),
                ('like', models.PositiveIntegerField(default=0)),
                ('comment', models.PositiveIntegerField(default=0)),
                ('releaseTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('authorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
                ('cateId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article', to='article.ArticleCategory')),
            ],
            options={
                'db_table': 'article',
            },
        ),
    ]
