# Generated by Django 2.2.7 on 2022-08-16 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20220816_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='authorId',
            field=models.ForeignKey(db_column='authorId', on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
        migrations.AlterField(
            model_name='article',
            name='cateId',
            field=models.ForeignKey(blank=True, db_column='cateId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article', to='article.ArticleCategory'),
        ),
    ]
