# Generated by Django 2.2.7 on 2022-08-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(blank=True, max_length=11)),
                ('userPhone', models.CharField(blank=True, max_length=11, unique=True)),
                ('userPassword', models.CharField(max_length=30)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='')),
                ('user_desc', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
